### ISSUE TITLE
Add schema.org to xmlns

### ISSUE THREAD

**Issue by alexmsenger** [lehkost/DNBTitel-Elasticsearch#2]
The `schema:` prefix isn't bound so parsers will complain. One need to amend the following line

https://github.com/lehkost/DNBTitel-Elasticsearch/blob/1aa09657fc3badf20da2084964b8b00f1f8eba01/dnb2es/split.sh#L18

and add `xmlns:schema="http://schema.org/"` to it. The result will look like the following: 

```sh 
  echo '<rdf:RDF xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:geo="http://www.opengis.net/ont/geosparql#" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:sf="http://www.opengis.net/ont/sf#" xmlns:isbd="http://iflastandards.info/ns/isbd/elements/" xmlns:gndo="http://d-nb.info/standards/elementset/gnd#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:marcRole="http://id.loc.gov/vocabulary/relators/" xmlns:lib="http://purl.org/library/" xmlns:umbel="http://umbel.org/umbel#" xmlns:rdau="http://rdaregistry.info/Elements/u/" xmlns:bibo="http://purl.org/ontology/bibo/" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:schema="http://schema.org/">' >> $filename
```

**Comment by alexmsenger** [comment]
Actually more prefixes are missing: 

1. `dnbt:ismn` binds to `http://d-nb.info/standards/elementset/dnb#ismn`
2. `mo:lc` binds to `http://purl.org/ontology/mo/lc`
3. `ebu:duration` to `http://semantic.eurobau.com/eurobau-utility.owl#duration`

according to prefix.cc. Will update this in case I encounter more.

**Comment by lehkost** [comment]
Thanks, @alexmsenger (and hi @ubbo) – feel free to send a pull request once you're finished. Also looking forward to your results.
